### ISSUE TITLE
Namespaced models

### ISSUE THREAD

**Issue by brandonweiss** [macfanatic/motion_data_wrapper#12]
Unfortunately I am forced to namespace my application (and my models) because some of my domain terminology collides with Ruby classes (like `Set`). This raises an error [here](https://github.com/macfanatic/motion_data_wrapper/blob/master/lib/motion_data_wrapper/delegate.rb#L24), and eventually fails with "executeFetchRequest:error: A fetch request must have an entity.", which I'm not familiar with. Is this a problem with my data model, or because I'm namespacing the model classes, which doesn't currently work?

**Comment by macfanatic** [comment]
The line you linked to [here](https://github.com/macfanatic/motion_data_wrapper/blob/master/lib/motion_data_wrapper/delegate.rb#L24) means that namespaced models are not supported at this time.

Ideally we would look outside Kernel to find those classes in a module :)

**Comment by brandonweiss** [comment]
I actually tweaked that line to work, but still got the "executeFetchRequest:error: A fetch request must have an entity" error. This is my first time using CoreData, so I couldn't tell if that was an issue with my model file/setup in Xcode, or if it was failing somewhere else in the library because my model classes are namespaced.

**Comment by macfanatic** [comment]
Essentially the class you have defined in code does not match up to the entity you named in the Xcode data modeler.  Since I've never worked with models in modules, I can't tell you if that's the culprit or not, but definitely a good possibility.

I would double check the entity name in Xcode.  You could also check out [this line](https://github.com/macfanatic/motion_data_wrapper/blob/master/lib/motion_data_wrapper/model/core_data.rb#L12) in REPL while running the simulator to see what values are returned, might point you in a good direction.

**Comment by brandonweiss** [comment]
Yes, that was it! So, that line fails because `name` returns something like "Namespace::Set". Which obviously is not the name of the entity. I could fix that by simply overriding the name method to return the specific name of the entity.

As for the constant lookup, is that necessary? If it fails it just sets the name to "Model". If it is necessary, maybe it should use `const_defined?`?

**Comment by macfanatic** [comment]
That's a good suggestion, and a great workaround might be overriding `#name` as you mentioned.  Setting to `Model` is probably what you get by default in CoreData without any customization, not sure.
